name: ItemsCoreU
version: '${project.version}'
main: me.udnek.itemscoreu.ItemsCoreU
api-version: '1.20'
depend: [ ProtocolLib ]
commands:
  giveu:
    description: "giveu"
    usage: "/giveu <item>"
    aliases: [itemscoreugive]
    permission: itemscoreu.admin
    permission-message: "You do not have permission to use this command"
  summonu:
    description: "summonu"
    usage: "/summonu <entity>"
    aliases: [itemscoreusummon]
    permission: itemscoreu.admin
    permission-message: "You do not have permission to use this command"