name: ItemsCoreU
version: '${project.version}'
main: me.udnek.itemscoreu.ItemsCoreU
api-version: '1.21.1'
depend: [ ProtocolLib ]
load: STARTUP
commands:
  helpu:
    description: "helpu"
    usage: "/helpu"
    aliases: [ itemscoreuhelp, ?, h ]
    permission-message: "You do not have permission to use this command"
  giveu:
    description: "giveu"
    usage: "/giveu <item>"
    aliases: [itemscoreugive]
    permission: itemscoreu.admin
    permission-message: "You do not have permission to use this command"
  summonu:
    description: "summonu"
    usage: "/summonu <entity>"
    aliases: [itemscoreusummon]
    permission: itemscoreu.admin
    permission-message: "You do not have permission to use this command"
  custom_entities:
      description: "custom_entities"
      usage: "/custom_entities"
      aliases: []
      permission: itemscoreu.admin
      permission-message: "You do not have permission to use this command"
  resourcepacku:
    description: "resourcepacku"
    usage: "/resourcepacku <directory>"
    aliases: [ itemscoreuresourcepack ]
    permission: itemscoreu.admin
    permission-message: "You do not have permission to use this command"
  attributeu:
      description: "attributeu"
      usage: "/attributeu <attribute>"
      aliases: [ itemscoreuattributeu ]
      permission: itemscoreu.admin
      permission-message: "You do not have permission to use this command"
  clear_attribute_modifiers:
      description: "cleat_attribute_modifiers"
      usage: "/cleat_attribute_modifiers"
      aliases: []
      permission: itemscoreu.admin
      permission-message: "You do not have permission to use this command"